<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- 独立发布：单文件 + 裁剪，减小体积 -->
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <!-- Windows Forms 不支持裁剪 -->
    <!--<PublishTrimmed>true</PublishTrimmed>-->
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>

    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <!-- 管理员权限 -->
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

</Project>
